### ISSUE TITLE
add progress events

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/hyperdrive-import-files#3]
- [ ] `file-counted(stats)`
- [ ] `file-added(stats)`
- [ ] `file-exists(stats)`

anything else?

cc @joehand

**Comment by joehand** [comment]
@juliangruber not sure we need both `file-added` and `file-exists` (I started to take that out from Dat but got distracted), but would need to emit `file-added` for both. There could be a flag in stats, `exists = true`, or something. 

Do you think it makes sense to do `file-counted` in here? It can be pretty slow since you have to iterate over the directories twice (once to count, once to append).

**Comment by juliangruber** [comment]
> Do you think it makes sense to do file-counted in here? It can be pretty slow since you have to iterate over the directories twice (once to count, once to append).

yeah i was thinking about that, currently this module doesn't do 2 passes like that.

I guess the crucial events are

- `start` (a given)
- `finished importing`
- `imported a new file`

**Comment by juliangruber** [comment]
so far you can do this:

```js
console.log('START')
const status = hyperImport(archive, process.argv.slice(2), err => {
  console.log('FINISHED IMPORTING')
})
status.on('file imported', file => {
  console.log('IMPORTED', file)
  console.log('FILE COUNT', status.fileCount)
  console.log('TOTAL SIZE', status.totalSize)
})
```

is that ok for dat?

**Comment by joehand** [comment]
@juliangruber looks great!

**Comment by joehand** [comment]
Maybe add a note to the readme saying that `status.on('file imported')` emits for live file additions *and* file changes, as that isn't intuitive.

**Comment by juliangruber** [comment]
@joehand there's the `existed` argument now, does that make more sense? i also updated the example above

**Comment by juliangruber** [comment]
i should probably rename that to `updated`

**Comment by joehand** [comment]
👍 updated makes more sense.

**Comment by juliangruber** [comment]
this is live now in 1.6.0 :)
