### ISSUE TITLE
dryRun option

### ISSUE THREAD

**Issue by pfrazee** [juliangruber/hyperdrive-import-files#32]
Would you be against a PR for a dryRun boolean option, which would run through the process but not write any updates to the archive? That would give me a simple 'diff' mechanism.

**Comment by juliangruber** [comment]
Sounds good to me! Just for full understanding, can you explain why you could use that diff mechanism?

**Comment by pfrazee** [comment]
I can watch the status object's emits, and find out which objects *would* change

**Comment by juliangruber** [comment]
ok!
