### ISSUE TITLE
index option on write stream

### ISSUE THREAD

**Issue by joehand** [juliangruber/hyperdrive-import-files#35]
> •mafintosh> jhand: just noticed that https://github.com/juliangruber/hyperdrive-import-files/blob/master/index.js#L85 does not set indexing: true on the write stream
> •mafintosh> jhand: we should add an option for that. will speed up imports a lot

https://botbot.me/freenode/dat/2016-12-22/?msg=78342893&page=3

**Comment by juliangruber** [comment]
nice! can someone explain to me what the indexing option does? I couldn't find an implementation in the hyperdrive repo

**Comment by joehand** [comment]
> mafintosh: because without that flag it'll rewrite the data to the file when adding it to a dat
> since it doesn't know that dest === src

So I think it just reads rather than read/write?
