### ISSUE TITLE
chokidar awaitWriteFinish option

### ISSUE THREAD

**Issue by joehand** [juliangruber/hyperdrive-import-files#42]
The `awaitWriteFinish` [option on chokidar](https://github.com/paulmillr/chokidar#performance) looks like something we may want to use to avoid polluting the metadata feed and adding the same file multiple times when it should be added once.

> By default, the add event will fire when a file first appear on disk, before the entire file has been written. Furthermore, in some cases some change events will be emitted while the file is being written. In some cases, especially when watching for large files there will be a need to wait for the write operation to finish before responding to a file creation or modification. Setting awaitWriteFinish to true (or a truthy value) will poll file size, holding its add and change events until the size does not change for a configurable amount of time. The appropriate duration setting is heavily dependent on the OS and hardware. For accurate detection this parameter should be relatively high, making file watching much less responsive. Use with caution.

Curious what others think about this.

**Comment by juliangruber** [comment]
made obsolete by https://github.com/juliangruber/hyperdrive-import-files/pull/44
