### ISSUE TITLE
Prefix causing files to get duplicated into directory

### ISSUE THREAD

**Issue by joehand** [juliangruber/hyperdrive-import-files#9]
Using this with Dat all my files get duplicated into the directory I'm trying to share. I think this is because of how the prefixes are being handled and [this line](https://github.com/juliangruber/hyperdrive-import-files/blob/master/index.js#L63).

I'm using it like this:
```js
var dir = '/Users/joe/Desktop/data_to_share'
var status = hyperImport(archive, [dir], done)
```
If I run that, I end up with `data_to_share/data_to_share` as duplicated data from the hyperdrive write.

**Comment by joehand** [comment]
Ah! Just realized it was because of how I was initiating my archive:

```js
drive.createArchive(key, {
      live: true,
      file: function (name) {
        return raf(path.join(self.dir, name))
      }
    }
```

But I am wondering if there should be an option to disable the prefix (or if I can initiate someway different)? I think as it is written, you'd get the root folder downloaded.

**Comment by joehand** [comment]
Well, that didn't totally solve it, it depends on where I run Dat. 

If I run the process in the directory I am sharing then it duplicates it.

**Comment by juliangruber** [comment]
Interesting. I haven't run into this issue as I was _always_ creating a copy of the data, which needs to change anyway.

I was thinking about changing the prefix logic so that if it's just a single dir, it will change to `./`. I'll give this a go and report back here.
